### ISSUE TITLE
Shader works in game view only in play mode

### ISSUE THREAD

**Issue by oliverellmers** [andydbc/unity-frosted-glass#1] opened 2018-03-28 15:47 UTC
Hello,

This looks really cool! I have been trying to get the demo scene working, but it does not seem to work when i hit play - you ust get a greay material on the glass object in the game view. It seems to work fine / you can see the effect well while not in play mode.

Any tips or tricks I might be missing?

thankyou!

Oliver

**Comment by andydbc** [comment] 2018-03-29 15:05
Hello @oliverellmers,
What you describe seem to be a known issue, can you confirm the effect is working properly in the game view, but not in the editor view ? If so, this bug is related to Unity and I'm not sure I can do much about it...

**Comment by oliverellmers** [comment] 2018-03-29 15:11
Hi @andydbc,

It is working correctly in the game view, but not in deitor - but will not work while in play mode / when the play button has been pressed.

Cheers

O.

**Comment by andydbc** [comment] 2018-03-29 15:17
I see, what version of Unity are you working with ?

**Comment by oliverellmers** [comment] 2018-03-29 15:20
I am using 2017.3.1f1

cheers

**Comment by andydbc** [comment] 2018-03-29 22:24
I tried with the same version on my side, and apart from the known issue about the Scene view (related to Unity) I am not able to reproduce it. I tried to make a build, and it worked fine too.

Here is a sceenshot in game view: 

![unity 2017 3 1f1 personal 64bit - demo unity - unity-frosted-glass - pc mac linux standalone dx11](https://user-images.githubusercontent.com/31256170/38116488-46a46c12-337e-11e8-9293-e5b042019863.jpg)

Do you notice any warnings or errors in the console ?

**Comment by andydbc** [comment] 2018-07-03 15:39
Should be fixed with : a9b894dc3fd10f1dadda97e5205af4d1b3112944

**Closed as completed by andydbc** 2018-07-03 15:39 UTC
Labels: bug
